<a href="https://colab.research.google.com/github/likhitha867/AI-Estate-Vision/blob/main/GridSearchCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df=sns.load_dataset('iris')

In [4]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [6]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x=df.drop(['species'],axis=1)

In [9]:
y=df['species']

In [10]:
x_train, x_test, y_train, y_test = train_test_split(
x, y, test_size=0.33, random_state=42)

In [11]:
from sklearn.neighbors import KNeighborsClassifier

In [12]:
model_knn= KNeighborsClassifier()

In [13]:
model_knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [14]:
model_knn.score(x_test,y_test)

1.0

In [15]:
from sklearn.svm import SVC

In [16]:
model_svm = SVC(gamma='auto')

In [17]:
model_svm.fit(x_train,y_train)

SVC(gamma='auto')

In [18]:
model_svm.score(x_test,y_test)

1.0

In [19]:
from sklearn.model_selection import GridSearchCV

In [20]:
classifier=GridSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel':['linear','rbf','poly'],
},cv=5,return_train_score=False)

In [21]:
classifier.fit(x,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30],
                         'kernel': ['linear', 'rbf', 'poly']})

In [22]:
classifier.cv_results_

{'mean_fit_time': array([0.01581783, 0.0131186 , 0.02288227, 0.02044592, 0.00895715,
        0.02115445, 0.00337734, 0.00750899, 0.05332928, 0.01061153,
        0.01193199, 0.04353318]),
 'std_fit_time': array([0.00715535, 0.00830283, 0.00616253, 0.00693503, 0.0022128 ,
        0.01391119, 0.0001647 , 0.00292076, 0.03588082, 0.00593412,
        0.00825075, 0.02945445]),
 'mean_score_time': array([0.00969152, 0.00865183, 0.01577401, 0.01643744, 0.00866075,
        0.00774217, 0.00270782, 0.00865407, 0.01169853, 0.00672579,
        0.00797052, 0.01149354]),
 'std_score_time': array([0.00189753, 0.00412827, 0.0050501 , 0.00602803, 0.00422159,
        0.00429301, 0.00013732, 0.00384649, 0.00392926, 0.00307196,
        0.00371498, 0.00615233]),
 'param_C': masked_array(data=[1, 1, 1, 10, 10, 10, 20, 20, 20, 30, 30, 30],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['linear', 'rbf', 'poly', 'linear', 'rbf', 'poly',
                    'linear', 'rbf', 'poly', 'linear', 'rbf', 'poly'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'poly'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'poly'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'poly'},
  {'C': 30, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'poly'}],
 'split0_test_score': array([0.96666667, 0.96666667, 1.        , 1.        , 0.96666667,
        1.        , 1.        , 0.96666667, 0.96666667, 1.        ,
        0.96666667, 0.96666667]),
 'split1_test_score': array([1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 0.96666667, 1.        ,
        1.        , 0.96666667]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.9       , 0.9       , 0.96666667,
        0.9       , 0.9       , 0.9       , 0.9       , 0.9       ,
        0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.96666667, 0.93333333, 0.9       ,
        0.93333333, 0.93333333]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.96666667, 0.97333333, 0.98      ,
        0.96666667, 0.96666667, 0.96666667, 0.95333333, 0.96      ,
        0.96      , 0.95333333]),
 'std_test_score': array([0.01632993, 0.01632993, 0.0421637 , 0.03887301, 0.01632993,
        0.0421637 , 0.0421637 , 0.03651484, 0.03399346, 0.04898979,
        0.03887301, 0.03399346]),
 'rank_test_score': array([ 1,  1,  6,  4,  1,  6,  6,  5, 11,  9,  9, 11], dtype=int32)}

In [23]:
results=pd.DataFrame(classifier.cv_results_)

In [24]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.015818,0.007155,0.009692,0.001898,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.013119,0.008303,0.008652,0.004128,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.022882,0.006163,0.015774,0.005050,1,poly,"{'C': 1, 'kernel': 'poly'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
3,0.020446,0.006935,0.016437,0.006028,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.008957,0.002213,0.008661,0.004222,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
5,0.021154,0.013911,0.007742,0.004293,10,poly,"{'C': 10, 'kernel': 'poly'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.003377,0.000165,0.002708,0.000137,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
7,0.007509,0.002921,0.008654,0.003846,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,5
8,0.053329,0.035881,0.011699,0.003929,20,poly,"{'C': 20, 'kernel': 'poly'}",0.966667,0.966667,0.900000,0.933333,1.0,0.953333,0.033993,11
9,0.010612,0.005934,0.006726,0.003072,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.900000,1.0,0.960000,0.048990,9
10,0.011932,0.008251,0.007971,0.003715,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.933333,1.0,0.960000,0.038873,9
11,0.043533,0.029454,0.011494,0.006152,30,poly,"{'C': 30, 'kernel': 'poly'}",0.966667,0.966667,0.900000,0.933333,1.0,0.953333,0.033993,11

In [25]:
classifier.best_params_

{'C': 1, 'kernel': 'linear'}

In [26]:
classifier.best_score_

np.float64(0.9800000000000001)

In [29]:
knn=GridSearchCV((model_knn),{
    'n_neighbors':[3,5,7,10,13],
    'weights':['uniform','distance'],
     'algorithm':['auto','ball_tree','kd_tree','brute'],
    'metric':['minkowski','euclidean','manhattan']
},cv=5,return_train_score=True)

In [30]:
knn.fit(x,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=13),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'metric': ['minkowski', 'euclidean', 'manhattan'],
                         'n_neighbors': [3, 5, 7, 10, 13],
                         'weights': ['uniform', 'distance']},
             return_train_score=True)

In [31]:
knn.cv_results_

{'mean_fit_time': array([0.00587478, 0.00426965, 0.00495896, 0.00418787, 0.0038662 ,
        0.00393672, 0.00652776, 0.00939908, 0.00857978, 0.00487304,
        0.00305738, 0.00704584, 0.00792232, 0.01013837, 0.00697718,
        0.00704918, 0.00421467, 0.00385427, 0.00344095, 0.00775609,
        0.00774746, 0.00590568, 0.00752854, 0.00848279, 0.00952868,
        0.00599279, 0.00333838, 0.0029212 , 0.00295792, 0.00329299,
        0.00306029, 0.00337176, 0.00346575, 0.00341263, 0.00372119,
        0.00324788, 0.00375185, 0.00323105, 0.00334277, 0.00332909,
        0.00296998, 0.00206909, 0.00211549, 0.0020628 , 0.00218892,
        0.00221181, 0.00222201, 0.00214119, 0.00234022, 0.00234241,
        0.00224214, 0.0022119 , 0.00300083, 0.00263553, 0.00215592,
        0.00225816, 0.00222034, 0.00225272, 0.00225592, 0.00213428,
        0.00209494, 0.00209484, 0.00210962, 0.00213528, 0.00213628,
        0.00203295, 0.00223069, 0.00212274, 0.00213799, 0.00215535,
        0.0021028 , 0.00219474, 0.00211678, 0.00199227, 0.00201764,
        0.00204754, 0.00256815, 0.00267949, 0.00240431, 0.00209641,
        0.00206771, 0.00207653, 0.00206313, 0.00209808, 0.00214438,
        0.0020978 , 0.00205307, 0.00214257, 0.00213475, 0.00204625,
        0.00198064, 0.00198765, 0.00194216, 0.00197797, 0.00190191,
        0.00190349, 0.00187583, 0.00182943, 0.00183282, 0.00213323,
        0.00217147, 0.00198627, 0.0026454 , 0.00186653, 0.00196805,
        0.00194974, 0.0019146 , 0.00190144, 0.00191879, 0.00187502,
        0.00190697, 0.00194807, 0.0019733 , 0.00198565, 0.00194836,
        0.00188203, 0.00188913, 0.00192127, 0.00194588, 0.00194941]),
 'std_fit_time': array([3.52633509e-03, 2.33999274e-04, 1.90680230e-03, 4.18902418e-04,
        1.26835547e-04, 8.78112684e-05, 5.06891085e-03, 1.31601489e-03,
        2.39078027e-03, 1.54206277e-03, 6.46341467e-05, 2.43511288e-03,
        9.56458374e-04, 1.57650469e-03, 9.70650961e-04, 7.51866915e-04,
        2.05292151e-03, 1.61510941e-03, 3.66066821e-04, 3.16531876e-04,
        2.56533696e-03, 2.24865476e-03, 1.39274267e-03, 2.40350223e-03,
        3.33532701e-03, 1.35300029e-03, 2.76610905e-04, 6.60695008e-05,
        8.27531071e-05, 4.46782203e-04, 3.48186983e-04, 8.57300584e-04,
        2.79523170e-04, 3.57284050e-04, 4.20584900e-04, 2.36964925e-04,
        5.43864513e-04, 1.55428800e-04, 1.12923919e-04, 6.92794342e-05,
        6.17709972e-04, 7.28531030e-05, 1.04640282e-04, 6.06796596e-05,
        1.65145513e-04, 8.19233438e-05, 9.40360355e-05, 2.55089608e-05,
        2.16382618e-04, 1.54799688e-04, 1.83750385e-04, 5.79798691e-05,
        6.59838958e-04, 6.24983487e-04, 1.99147887e-05, 5.97586740e-05,
        3.37678151e-05, 1.47628476e-04, 3.79303983e-04, 1.15929636e-04,
        4.86047486e-05, 5.01746448e-05, 7.00526531e-05, 5.68115005e-05,
        5.88175107e-05, 1.85693638e-05, 1.40796650e-04, 8.00787779e-05,
        4.51246701e-05, 1.05493731e-04, 1.09286500e-04, 1.66995875e-04,
        1.02115832e-04, 1.33458194e-05, 3.86387007e-05, 2.39137519e-05,
        3.59814653e-04, 6.20226522e-04, 5.61015130e-04, 7.66624551e-05,
        2.97954933e-05, 4.91680387e-05, 3.76890232e-05, 6.49981696e-05,
        3.29129573e-05, 4.83822676e-05, 3.77952935e-05, 1.47407604e-04,
        7.83225027e-05, 4.05167386e-05, 1.09085356e-04, 9.84421507e-05,
        6.53066744e-05, 1.29361395e-04, 1.93253812e-05, 9.02298129e-05,
        2.07817866e-05, 1.74703400e-05, 1.81314782e-05, 3.14690221e-04,
        2.33969101e-04, 4.33570594e-05, 5.53052658e-04, 2.00619849e-05,
        5.75496424e-05, 4.07140197e-05, 7.82606725e-05, 6.21325221e-05,
        2.41573441e-05, 5.49606488e-05, 2.88352857e-05, 3.29222822e-05,
        5.17041019e-05, 1.10296321e-04, 7.75377395e-05, 2.05546131e-05,
        7.28941324e-05, 5.27905468e-05, 8.01108564e-05, 8.63002279e-05]),
 'mean_score_time': array([0.00677896, 0.00475945, 0.00546131, 0.00417471, 0.00587015,
        0.00446811, 0.00686326, 0.01027865, 0.01102376, 0.0069375 ,
        0.00436339, 0.00720553, 0.0087193 , 0.01168418, 0.00946641,
        0.00697002, 0.00561986, 0.0036346 , 0.00535398, 0.00925393,
        0.00866919, 0.00729742, 0.01091771, 0.0086709 , 0.00841727,
        0.0067193 , 0.00514288, 0.00316868, 0.00411997, 0.00353823,
        0.00395007, 0.00361848, 0.00463061, 0.00410948, 0.00474777,
        0.00338688, 0.0047163 , 0.00350685, 0.00449758, 0.00389957,
        0.00405717, 0.00234537, 0.00298157, 0.00231495, 0.00304461,
        0.00244823, 0.00322704, 0.0024087 , 0.00345044, 0.00248723,
        0.0030827 , 0.00253887, 0.00429001, 0.00324607, 0.00307622,
        0.00243859, 0.00326996, 0.00252385, 0.00303741, 0.0023735 ,
        0.00300546, 0.00227666, 0.00303097, 0.00243578, 0.00297818,
        0.00230961, 0.00311236, 0.00249462, 0.00301418, 0.00241504,
        0.00289974, 0.00241489, 0.00290341, 0.00231819, 0.00294886,
        0.00225463, 0.00352268, 0.00328469, 0.00306792, 0.0022862 ,
        0.00297594, 0.00234151, 0.00301104, 0.00234756, 0.00310154,
        0.00226955, 0.00299449, 0.00237961, 0.00296102, 0.00223923,
        0.01273351, 0.00225067, 0.0030364 , 0.00231094, 0.00284729,
        0.0023911 , 0.00294785, 0.00215755, 0.00283022, 0.00257225,
        0.00317492, 0.00227861, 0.00387897, 0.0021987 , 0.00295696,
        0.00229397, 0.00288119, 0.00226946, 0.00298166, 0.00223541,
        0.00287304, 0.00219297, 0.0028522 , 0.00227547, 0.00283647,
        0.00210896, 0.00287499, 0.00217304, 0.00301652, 0.00218282]),
 'std_score_time': array([2.67546515e-03, 6.06190827e-04, 1.23206786e-04, 1.47606019e-04,
        4.90575700e-04, 4.90378870e-04, 2.75886215e-03, 1.38017715e-03,
        2.33131505e-03, 3.11213569e-03, 1.30692845e-04, 2.28789325e-03,
        1.86951887e-03, 3.70495766e-03, 7.85300176e-04, 1.11825632e-03,
        2.23183541e-03, 2.22364643e-04, 1.55136586e-03, 1.15533118e-03,
        4.92242553e-03, 2.29204842e-03, 3.23198486e-03, 1.68926974e-03,
        1.91053384e-03, 1.83369118e-03, 1.08634590e-03, 6.45308150e-05,
        2.46896685e-05, 4.41752263e-04, 1.10204939e-04, 4.27657035e-04,
        3.91641526e-04, 8.79003363e-04, 3.00989556e-04, 6.02856105e-04,
        1.08463066e-04, 5.43360911e-05, 1.66541711e-04, 2.64713175e-04,
        8.85409476e-04, 1.10597381e-04, 1.32292418e-04, 5.41027601e-05,
        8.58249927e-05, 7.02511742e-05, 2.73345519e-04, 3.28476087e-05,
        3.73209219e-04, 1.81993346e-04, 5.93054702e-05, 6.41494684e-05,
        6.78930294e-04, 6.25828071e-04, 4.29229200e-05, 4.95863417e-05,
        1.66358596e-04, 3.82723578e-04, 2.19359263e-04, 4.34488409e-05,
        2.27410105e-04, 3.16348304e-05, 2.32980869e-04, 4.29816793e-05,
        8.64894541e-05, 3.48598294e-05, 5.68919687e-05, 2.77633021e-04,
        3.57756909e-05, 1.32739732e-04, 8.84795214e-05, 4.46176404e-05,
        8.32027417e-05, 7.16961416e-05, 8.37810622e-05, 4.55754061e-05,
        4.88271993e-04, 6.89795376e-04, 1.49361611e-04, 3.64859890e-05,
        8.63645428e-05, 2.75234604e-05, 2.41436427e-04, 3.16860355e-05,
        1.42008751e-04, 3.75578208e-05, 5.99787227e-05, 1.20239706e-04,
        3.58737496e-05, 4.21131175e-05, 1.95841999e-02, 4.55505543e-05,
        1.16570312e-04, 8.41451283e-05, 4.60283971e-05, 3.40853560e-04,
        1.64744402e-04, 2.56583589e-05, 4.51062244e-05, 3.84747472e-04,
        4.01625805e-04, 4.58962639e-05, 6.36235113e-04, 5.72111202e-05,
        5.90544291e-05, 6.10512846e-05, 4.67238617e-05, 4.55636307e-05,
        4.26461466e-05, 6.74459149e-05, 2.34473083e-04, 2.49440988e-05,
        3.24094960e-05, 7.58900981e-05, 1.06716433e-04, 5.97643810e-05,
        1.95487103e-04, 6.51626546e-05, 2.20188530e-04, 2.44067039e-05]),
 'param_algorithm': masked_array(data=['auto', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto',
                    'auto', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto',
                    'auto', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto',
                    'auto', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto',
                    'auto', 'auto', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_metric': masked_array(data=['minkowski', 'minkowski', 'minkowski', 'minkowski',
                    'minkowski', 'minkowski', 'minkowski', 'minkowski',
                    'minkowski', 'minkowski', 'euclidean', 'euclidean',
                    'euclidean', 'euclidean', 'euclidean', 'euclidean',
                    'euclidean', 'euclidean', 'euclidean', 'euclidean',
                    'manhattan', 'manhattan', 'manhattan', 'manhattan',
                    'manhattan', 'manhattan', 'manhattan', 'manhattan',
                    'manhattan', 'manhattan', 'minkowski', 'minkowski',
                    'minkowski', 'minkowski', 'minkowski', 'minkowski',
                    'minkowski', 'minkowski', 'minkowski', 'minkowski',
                    'euclidean', 'euclidean', 'euclidean', 'euclidean',
                    'euclidean', 'euclidean', 'euclidean', 'euclidean',
                    'euclidean', 'euclidean', 'manhattan', 'manhattan',
                    'manhattan', 'manhattan', 'manhattan', 'manhattan',
                    'manhattan', 'manhattan', 'manhattan', 'manhattan',
                    'minkowski', 'minkowski', 'minkowski', 'minkowski',
                    'minkowski', 'minkowski', 'minkowski', 'minkowski',
                    'minkowski', 'minkowski', 'euclidean', 'euclidean',
                    'euclidean', 'euclidean', 'euclidean', 'euclidean',
                    'euclidean', 'euclidean', 'euclidean', 'euclidean',
                    'manhattan', 'manhattan', 'manhattan', 'manhattan',
                    'manhattan', 'manhattan', 'manhattan', 'manhattan',
                    'manhattan', 'manhattan', 'minkowski', 'minkowski',
                    'minkowski', 'minkowski', 'minkowski', 'minkowski',
                    'minkowski', 'minkowski', 'minkowski', 'minkowski',
                    'euclidean', 'euclidean', 'euclidean', 'euclidean',
                    'euclidean', 'euclidean', 'euclidean', 'euclidean',
                    'euclidean', 'euclidean', 'manhattan', 'manhattan',
                    'manhattan', 'manhattan', 'manhattan', 'manhattan',
                    'manhattan', 'manhattan', 'manhattan', 'manhattan'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_n_neighbors': masked_array(data=[3, 3, 5, 5, 7, 7, 10, 10, 13, 13, 3, 3, 5, 5, 7, 7, 10,
                    10, 13, 13, 3, 3, 5, 5, 7, 7, 10, 10, 13, 13, 3, 3, 5,
                    5, 7, 7, 10, 10, 13, 13, 3, 3, 5, 5, 7, 7, 10, 10, 13,
                    13, 3, 3, 5, 5, 7, 7, 10, 10, 13, 13, 3, 3, 5, 5, 7, 7,
                    10, 10, 13, 13, 3, 3, 5, 5, 7, 7, 10, 10, 13, 13, 3, 3,
                    5, 5, 7, 7, 10, 10, 13, 13, 3, 3, 5, 5, 7, 7, 10, 10,
                    13, 13, 3, 3, 5, 5, 7, 7, 10, 10, 13, 13, 3, 3, 5, 5,
                    7, 7, 10, 10, 13, 13],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_weights': masked_array(data=['uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'algorithm': 'auto',
   'metric': 'minkowski',
   'n_neighbors': 3,
   'weights': 'uniform'},
  {'algorithm': 'auto',
   'metric': 'minkowski',
   'n_neighbors': 3,
   'weights': 'distance'},
  {'algorithm': 'auto',
   'metric': 'minkowski',
   'n_neighbors': 5,
   'weights': 'uniform'},
  {'algorithm': 'auto',
   'metric': 'minkowski',
   'n_neighbors': 5,
   'weights': 'distance'},
  {'algorithm': 'auto',
   'metric': 'minkowski',
   'n_neighbors': 7,
   'weights': 'uniform'},
  {'algorithm': 'auto',
   'metric': 'minkowski',
   'n_neighbors': 7,
   'weights': 'distance'},
  {'algorithm': 'auto',
   'metric': 'minkowski',
   'n_neighbors': 10,
   'weights': 'uniform'},
  {'algorithm': 'auto',
   'metric': 'minkowski',
   'n_neighbors': 10,
   'weights': 'distance'},
  {'algorithm': 'auto',
   'metric': 'minkowski',
   'n_neighbors': 13,
   'weights': 'uniform'},
  {'algorithm': 'auto',
   'metric': 'minkowski',
   'n_neighbors': 13,
   'weights': 'distance'},
  {'algorithm': 'auto',
   'metric': 'euclidean',
   'n_neighbors': 3,
   'weights': 'uniform'},

In [32]:
knn.best_params_

{'algorithm': 'auto',
 'metric': 'minkowski',
 'n_neighbors': 10,
 'weights': 'distance'}

In [33]:
knn.best_score_

np.float64(0.9866666666666667)

In [35]:
result=pd.DataFrame(knn.cv_results_)
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_metric,param_n_neighbors,param_weights,params,split0_test_score,...,mean_test_score,std_test_score,rank_test_score,split0_train_score,split1_train_score,split2_train_score,split3_train_score,split4_train_score,mean_train_score,std_train_score
0,0.005875,0.003526,0.006779,0.002675,auto,minkowski,3,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.966667,...,0.966667,0.021082,72,0.958333,0.958333,0.966667,0.966667,0.950000,0.960000,0.006236
1,0.004270,0.000234,0.004759,0.000606,auto,minkowski,3,distance,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.966667,...,0.966667,0.021082,72,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
2,0.004959,0.001907,0.005461,0.000123,auto,minkowski,5,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.966667,...,0.973333,0.024944,41,0.966667,0.966667,0.975000,0.975000,0.966667,0.970000,0.004082
3,0.004188,0.000419,0.004175,0.000148,auto,minkowski,5,distance,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.966667,...,0.966667,0.036515,72,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
4,0.003866,0.000127,0.005870,0.000491,auto,minkowski,7,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.966667,...,0.980000,0.016330,11,0.966667,0.966667,0.975000,0.983333,0.975000,0.973333,0.006236
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,0.001882,0.000021,0.002109,0.000060,brute,manhattan,7,distance,"{'algorithm': 'brute', 'metric': 'manhattan', ...",0.966667,...,0.960000,0.032660,101,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
116,0.001889,0.000073,0.002875,0.000195,brute,manhattan,10,uniform,"{'algorithm': 'brute', 'metric': 'manhattan', ...",0.966667,...,0.973333,0.024944,41,0.958333,0.966667,0.975000,0.975000,0.950000,0.965000,0.009718
117,0.001921,0.000053,0.002173,0.000065,brute,manhattan,10,distance,"{'algorithm': 'brute', 'metric': 'manhattan', ...",0.966667,...,0.966667,0.036515,72,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
118,0.001946,0.000080,0.003017,0.000220,brute,manhattan,13,uniform,"{'algorithm': 'brute', 'metric': 'manhattan', ...",0.933333,...,0.973333,0.024944,41,0.975000,0.966667,0.975000,0.975000,0.933333,0.965000,0.016159
119,0.001949,0.000086,0.002183,0.000024,brute,manhattan,13,distance,"{'algorithm': 'brute', 'metric': 'manhattan', ...",0.966667,...,0.966667,0.036515,72,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000

In [37]:
from sklearn.model_selection import RandomizedSearchCV

In [38]:
classifier_r=RandomizedSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel':['linear','rbf','poly'],
},n_iter=4,cv=5,return_train_score=False)

In [39]:
classifier_r.fit(x,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['linear', 'rbf', 'poly']})

In [42]:
results_r=pd.DataFrame(classifier_r.cv_results_)
results_r

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.012436,0.005448,0.004242,0.000464,poly,10,"{'kernel': 'poly', 'C': 10}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,2
1,0.019469,0.012531,0.003701,0.000502,poly,20,"{'kernel': 'poly', 'C': 20}",0.966667,0.966667,0.900000,0.933333,1.0,0.953333,0.033993,3
2,0.005341,0.000445,0.003679,0.000244,rbf,1,"{'kernel': 'rbf', 'C': 1}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.019254,0.012926,0.003370,0.000240,poly,30,"{'kernel': 'poly', 'C': 30}",0.966667,0.966667,0.900000,0.933333,1.0,0.953333,0.033993,3

In [43]:
classifier_r.best_params_

{'kernel': 'rbf', 'C': 1}

In [44]:
classifier_r.best_score_

np.float64(0.9800000000000001)